// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KlayButton: typeof import('./common/KlayButton.vue')['default']
    KlayCollapse: typeof import('./common/KlayCollapse.vue')['default']
    KlayIcon: typeof import('./common/KlayIcon.vue')['default']
    KlayLoader: typeof import('./common/KlayLoader.vue')['default']
    KlaySlider: typeof import('./common/KlaySlider.vue')['default']
    KlaySlippage: typeof import('./common/KlaySlippage.vue')['default']
    KlayTextField: typeof import('./common/KlayTextField.vue')['default']
    KlayWrap: typeof import('./common/KlayWrap.vue')['default']
    LiquidityModuleAdd: typeof import('./modules/LiquidityModule/Add/index.vue')['default']
    LiquidityModuleAddExchangeRate: typeof import('./components/LiquidityModule/Add/ExchangeRate.vue')['default']
    LiquidityModuleAddModal: typeof import('./components/LiquidityModule/Add/Modal.vue')['default']
    LiquidityModuleRemove: typeof import('./modules/LiquidityModule/Remove/index.vue')['default']
    LiquidityModuleRemoveAmount: typeof import('./components/LiquidityModule/Remove/Amount/index.vue')['default']
    LiquidityModuleRemoveDetailed: typeof import('./modules/LiquidityModule/Remove/Detailed/index.vue')['default']
    NotificationsInit: typeof import('./components/NotificationsInit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwapModule: typeof import('./components/SwapModule/index.vue')['default']
    SwapModuleDetails: typeof import('./components/SwapModule/Details/index.vue')['default']
    SwapModuleExchangeRate: typeof import('./components/SwapModule/ExchangeRate.vue')['default']
    TagName: typeof import('./components/TagName.vue')['default']
    TokenInput: typeof import('./components/TokenInput/index.vue')['default']
    TokenSelect: typeof import('./components/TokenSelect/index.vue')['default']
    TokenSelectModal: typeof import('./components/TokenSelect/Modal.vue')['default']
    Tutorial: typeof import('./components/Tutorial.vue')['default']
  }
}

export {}
