// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./components/liquidity/add/index.vue')['default']
    Amount: typeof import('./components/liquidity/remove/amount/index.vue')['default']
    Button: typeof import('./components/button/index.vue')['default']
    Collapse: typeof import('./components/collapse/index.vue')['default']
    Detailed: typeof import('./components/liquidity/remove/detailed/index.vue')['default']
    ExchangeRate: typeof import('./components/swap/exchange-rate/index.vue')['default']
    Icon: typeof import('./components/icon/index.vue')['default']
    Loader: typeof import('./components/loader/index.vue')['default']
    Menu: typeof import('./components/menu/index.vue')['default']
    Modal: typeof import('./components/modal/index.vue')['default']
    Remove: typeof import('./components/liquidity/remove/remove.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./components/slide/index.vue')['default']
    Slippage: typeof import('./components/slippage/index.vue')['default']
    Swap: typeof import('./components/swap/index.vue')['default']
    SwapDetails: typeof import('./components/swap/swap-details.vue')['default']
    SwapExchangeRate: typeof import('./components/liquidity/add/swap-exchange-rate.vue')['default']
    TagName: typeof import('./components/tag-name/index.vue')['default']
    TextField: typeof import('./components/text-field/index.vue')['default']
    TokenInput: typeof import('./components/token-input/index.vue')['default']
    TokenSelect: typeof import('./components/token-select/index.vue')['default']
    TokenSelectModal: typeof import('./components/token-select/token-select-modal.vue')['default']
    Tutorial: typeof import('./components/Tutorial.vue')['default']
    Wrap: typeof import('./components/wrap/index.vue')['default']
  }
}

export {}
